name: CheckAListLite

on:
  # schedule:
  #   - cron: "0 5,17 * * *" # 每日5点和17点执行
  # push:
  #   branches:
  #     - "master"
  #   paths:
  #     - "sync_alist.yaml"  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION_FILE: ${{ github.workspace }}/alist_version
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd $GITHUB_WORKSPACE/.github/scripts
          chmod +x ./*.sh

          if ! [ -s "$VERSION_FILE" ]; then
            echo "3.45.1" > "$VERSION_FILE"
          fi

          ./check_alist.sh

      - name: Check AListLite Update
        run: |
          if [ "$alist_update" -eq 0 ]; then
            echo "无更新"
          else
            echo -e "[自动同步AListLite] $alist_version" > $GITHUB_WORKSPACE/CHANGELOG.md
            echo -e "$alist_version" > "$VERSION_FILE"

            git config user.name "github-actions"
            git config user.email "18594370+GitCourser@users.noreply.github.com"
            git add .
            git commit -m "[bot] Update alist to $alist_version"
            git push
          fi
        env:
          alist_version: ${{ env.alist_version }}
          alist_update: ${{ env.alist_update }}

      - name: Run workflow release
        if: env.alist_update == 1 && ( success() || failure() )
        run: |
          gh workflow run release.yaml -R GitCourser/AListLiteTV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}